apiVersion: v1
kind: ReplicationController
metadata:
  name: odoo-rc
  labels:
   type: front-end
   app: odoo-app
spec:
 template:
   metadata:
     name: odoo-pod
     labels:
       type: front-end
       app: odooapp-pod
   spec:
    containers:
       - name: odoo-container
         image: nginx
 replicas: 3
